### ISSUE TITLE
Add option to prevent saving when a build is running

### ISSUE THREAD

**Issue by sliwowitz** [mystilleef/eclipse4-smartsave#13]
When a build is running and you attempt to save a file, a non-modal dialog box appears informing you the file will be saved after the build finishes.

You cannot do anything except:
 * wait for the build to finish (which might be a long time)
 * cancel the build (which is nbot what you wanted to do)
 * cancel the save (which is what you probably want to keep doint until the build finishes

You cannot use the editor or any other windows until you react to that dialog.

Autosave will trigger that dialog everytime it tries to save a file - in default configuration that means every 3 seconds you have to dismiss the dialog window by canceling the attempt to save a file which cannot be saved at the moment - not very smart.

This happens in CDT projects, maybe Java builds work in a different way and are unaffected by this.

An option should be present to make Smart Save not trying to save a file while a build is running.

**Comment by mystilleef** [comment]
This should be fixed in the latest release. If you're still having problems, please reopen.
