### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by holmesmi** [mystilleef/eclipse4-smartsave#16]
The update site specified in all the instructions (https://raw.github.com/mystilleef/eclipse4-smartsave-updatesite/master/com.laboki.eclipse.updatesite.smartsave) doesn't exist.

**Comment by DoHe** [comment]
Installing using Eclipse's built-in marketplace works fine

**Comment by holmesmi** [comment]
Not for me. 
Unable to read repository at https://raw.github.com/mystilleef/eclipse4-smartsave-updatesite/master/com.laboki.eclipse.updatesite.smartsave/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by DoHe** [comment]
The new update site seems to be:
https://raw.githubusercontent.com/mystilleef/eclipse4-smartsave-updatesite/master/com.laboki.eclipse.updatesite.smartsave

**Comment by holmesmi** [comment]
Marketplace seems to be working now. Yay!

**Comment by holmesmi** [comment]
@DoHe had left a comment with a new site, and it worked for a while. That comment was deleted, and neither site seems to be working at the moment.

**Comment by holmesmi** [comment]
The problem seems to be with my work not accepting an HTTPS connection. Good grief.
