### ISSUE TITLE
Does not seem to work in Eclipse Mars (4.5.1)

### ISSUE THREAD

**Issue by dlesaffre** [mystilleef/eclipse4-smartsave#18]
I tried installing both manually (add update site, ...) and with the Install button.
There is no SmartSave entry in any of the menus.

**Comment by KramKroc** [comment]
Same for Mars.2

**Comment by fabiojb** [comment]
It worked perfectly for me on neon 4.6.1

**Comment by dlesaffre** [comment]
I'm now on Mars.2 Release (4.5.2 Build id: 20160218-0600), and I do have a 'Disable Smart Save' item in the 'File' menu, and there is a page in the Windows Preferences.

Auto-saving seems to kick in too.

No longer an issue.
