### ISSUE TITLE
No preferences entry after install

### ISSUE THREAD

**Issue by TH-RBK** [mystilleef/eclipse4-smartsave#5]
Hi,

I installed the plugin without any error messages, but I could not find any entry in the preferences window.

I tried an uninstall and a new install (of course with restarting eclipse every time).

Eclipse Version: Juno Service Release 1
Windows 7 

If you need any more information just contact me.

**Comment by minibiti** [comment]
Hi, I am running Ubuntu 14.04 with Java 7 and Eclipse Luna and it does not work.
After the install, I do not see "Smart Save" in Windows->Preferences.
It is not in General->Startup and Shutdown either.

Any idea?

**Comment by minibiti** [comment]
Hi again,
I found and fixed the problem... I needed to run Eclipse with JDK 8 :)
