### ISSUE TITLE
Support filtering of auto-saved files (select which files are saved automatically)

### ISSUE THREAD

**Issue by lincolnthree** [mystilleef/eclipse4-smartsave#6]
Hey, nice plugin. It would really be cool if you could filter which tiles (by extension) are saved automatically. For instance, I want to save .txt files, but not .xml files.

Should be a pretty simple filter! It could just be a regex. Hopefully this is doable.

**Comment by mystilleef** [comment]
Okay, this is now implemented in the latest release. Check the preferences page to enable or disable which file types you want to automatically save.
