### ISSUE TITLE
Support sub-second autosave rates (Save as you type)

### ISSUE THREAD

**Issue by lincolnthree** [mystilleef/eclipse4-smartsave#7]
This, combined with Issue #6 would be a powerful feature to enable live-reload type features for live previews combined with other technologies!

(E.g, a tool that polls for file changes.)

**Comment by mystilleef** [comment]
1 second saving is the closest I can get without the craziness that can occur with constant saving e.g code reformatting etc. If 1 second saving doesn't work for you, please reopen.
