### ISSUE TITLE
Menu-bar toggle or "quick toggle" for Auto-Save

### ISSUE THREAD

**Issue by lincolnthree** [mystilleef/eclipse4-smartsave#9]
It would be nice to be able to toggle auto-save on and off without needing to go into the preferences, either with a few key-bindings, or preferably with a toggle button in the toolbar.

PS. really nice job on this plugin! I tried to work on a few issues but you use Lombok and I don't have that set up right now. (Is there really much benefit to using Lombok here? it presents a minor barrier to entry for contributors.)

**Comment by mystilleef** [comment]
There's now an option to toggle smart save on the toolbar, file menu and context menu.
